name: Docker CI Cloud Build

on:
  push:
    branches: ["main", "my_new_ci"]
  pull_request:
    branches: ["main"]

jobs:
  build-container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Setup Node.js Runtime
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'

    - name: Run Automated Application Tests
      run:
        npm ci
        npm test

    - name: Build the Docker Image
      run:
        docker build -t my-first-image:latest .
        echo "Docker image compiled successfully "
